import {
  FaJs,
  FaReact,
  FaNodeJs,
  FaDocker,
  FaCss3Alt,
  FaHtml5,
  FaGitAlt,
  FaGithub,
  FaBootstrap,
  FaPython,
} from "react-icons/fa";
import {
  SiPrisma,
  SiMongodb,
  SiRedis,
  SiExpress,
  SiTypescript,
  SiRabbitmq,
  SiJsonwebtokens,
  SiZod,
  SiDjango,
  SiFastapi,
  SiFlask,
  SiSqlalchemy
} from "react-icons/si";
import { RiNextjsFill } from "react-icons/ri";
import { RiTailwindCssFill } from "react-icons/ri";
import { BiLogoPostgresql } from "react-icons/bi";
import { FcLinux } from "react-icons/fc";

export const ICONS = [
  { icon: <FaHtml5 />, name: "HTML", colorClassName: "text-orange-600" },
  { icon: <FaCss3Alt />, name: "CSS", colorClassName: "text-blue-600" },
  { icon: <FaJs />, name: "JavaScript", colorClassName: "text-yellow-600" },
  { icon: <FaReact />, name: "React", colorClassName: "text-cyan-400" },
  { icon: <RiNextjsFill />, name: "Next.js", colorClassName: "text-black dark:text-white" },
  { icon: <RiTailwindCssFill />, name: "Tailwind CSS", colorClassName: "text-[#00FFFF]" },
  { icon: <FaNodeJs />, name: "Node.js", colorClassName: "text-green-600" },
  { icon: <SiTypescript />, name: "TypeScript", colorClassName: "text-[#377CC8]" },
  { icon: <SiExpress />, name: "Express", colorClassName: "text-black dark:text-white" },
  { icon: <SiZod />, name: "Zod", colorClassName: "text-blue-500"},
  { icon: <SiPrisma />, name: "Prisma", colorClassName: "text-[#000] dark:text-white" },
  { icon: <SiSqlalchemy />, name: "SQL Alchemy", colorClassName: "text-[#000] dark:text-white" },
  { icon: <FaPython />, name: "Python", colorClassName: "text-[#08668E]" },
  { icon: <SiDjango />, name: "Django", colorClassName: "text-[#2DA045]" },
  { icon: <SiFastapi />, name: "FastAPI", colorClassName: "text-[#39979c]" },
  { icon: <SiFlask />, name: "Flask", colorClassName: "text-black dark:text-white" },
  { icon: <SiRedis />, name: "Redis", colorClassName: "text-red-500" },
  { icon: <FaDocker />, name: "Docker", colorClassName: "text-blue-500" },
  { icon: <FaGitAlt />, name: "Git", colorClassName: "text-red-600" },
  { icon: <FaGithub />, name: "GitHub", colorClassName: "text-black dark:text-white" },
  { icon: <BiLogoPostgresql />, name: "PostgreSQL", colorClassName: "text-[#396C94]" },
  { icon: <SiMongodb />, name: "MongoDB", colorClassName: "text-[#2DA045]" },
  { icon: <SiJsonwebtokens />, name: "JSON Web Tokens", colorClassName: "text-[#EA185D]" },
  { icon: <FcLinux />, name: "Linux", colorClassName: "" },

  //2
  { icon: <FaHtml5 />, name: "HTML", colorClassName: "text-orange-600" },
  { icon: <FaCss3Alt />, name: "CSS", colorClassName: "text-blue-600" },
  { icon: <FaJs />, name: "JavaScript", colorClassName: "text-yellow-600" },
  { icon: <FaReact />, name: "React", colorClassName: "text-cyan-400" },
  { icon: <RiNextjsFill />, name: "Next.js", colorClassName: "text-black dark:text-white" },
  { icon: <RiTailwindCssFill />, name: "Tailwind CSS", colorClassName: "text-[#00FFFF]" },
  { icon: <FaNodeJs />, name: "Node.js", colorClassName: "text-green-600" },
  { icon: <SiTypescript />, name: "TypeScript", colorClassName: "text-[#377CC8]" },
  { icon: <SiExpress />, name: "Express", colorClassName: "text-black dark:text-white" },
  { icon: <SiZod />, name: "Zod", colorClassName: "text-blue-500"},
  { icon: <SiPrisma />, name: "Prisma", colorClassName: "text-[#000] dark:text-white" },
  { icon: <SiSqlalchemy />, name: "SQL Alchemy", colorClassName: "text-[#000] dark:text-white" },
  { icon: <FaPython />, name: "Python", colorClassName: "text-[#08668E]" },
  { icon: <SiDjango />, name: "Django", colorClassName: "text-[#2DA045]" },
  { icon: <SiFastapi />, name: "FastAPI", colorClassName: "text-[#39979c]" },
  { icon: <SiFlask />, name: "Flask", colorClassName: "text-black dark:text-white" },
  { icon: <SiRedis />, name: "Redis", colorClassName: "text-red-500" },
  { icon: <FaDocker />, name: "Docker", colorClassName: "text-blue-500" },
  { icon: <FaGitAlt />, name: "Git", colorClassName: "text-red-600" },
  { icon: <FaGithub />, name: "GitHub", colorClassName: "text-black dark:text-white" },
  { icon: <BiLogoPostgresql />, name: "PostgreSQL", colorClassName: "text-[#396C94]" },
  { icon: <SiMongodb />, name: "MongoDB", colorClassName: "text-[#2DA045]" },
  { icon: <SiJsonwebtokens />, name: "JSON Web Tokens", colorClassName: "text-[#EA185D]" },
  { icon: <FcLinux />, name: "Linux", colorClassName: "" },
  //3
  { icon: <FaHtml5 />, name: "HTML", colorClassName: "text-orange-600" },
  { icon: <FaCss3Alt />, name: "CSS", colorClassName: "text-blue-600" },
  { icon: <FaJs />, name: "JavaScript", colorClassName: "text-yellow-600" },
  { icon: <FaReact />, name: "React", colorClassName: "text-cyan-400" },
  { icon: <RiNextjsFill />, name: "Next.js", colorClassName: "text-black dark:text-white" },
  { icon: <RiTailwindCssFill />, name: "Tailwind CSS", colorClassName: "text-[#00FFFF]" },
  { icon: <FaNodeJs />, name: "Node.js", colorClassName: "text-green-600" },
  { icon: <SiTypescript />, name: "TypeScript", colorClassName: "text-[#377CC8]" },
  { icon: <SiExpress />, name: "Express", colorClassName: "text-black dark:text-white" },
  { icon: <SiZod />, name: "Zod", colorClassName: "text-blue-500"},
  { icon: <SiPrisma />, name: "Prisma", colorClassName: "text-[#000] dark:text-white" },
  { icon: <SiSqlalchemy />, name: "SQL Alchemy", colorClassName: "text-[#000] dark:text-white" },
  { icon: <FaPython />, name: "Python", colorClassName: "text-[#08668E]" },
  { icon: <SiDjango />, name: "Django", colorClassName: "text-[#2DA045]" },
  { icon: <SiFastapi />, name: "FastAPI", colorClassName: "text-[#39979c]" },
  { icon: <SiFlask />, name: "Flask", colorClassName: "text-black dark:text-white" },
  { icon: <SiRedis />, name: "Redis", colorClassName: "text-red-500" },
  { icon: <FaDocker />, name: "Docker", colorClassName: "text-blue-500" },
  { icon: <FaGitAlt />, name: "Git", colorClassName: "text-red-600" },
  { icon: <FaGithub />, name: "GitHub", colorClassName: "text-black dark:text-white" },
  { icon: <BiLogoPostgresql />, name: "PostgreSQL", colorClassName: "text-[#396C94]" },
  { icon: <SiMongodb />, name: "MongoDB", colorClassName: "text-[#2DA045]" },
  { icon: <SiJsonwebtokens />, name: "JSON Web Tokens", colorClassName: "text-[#EA185D]" },
  { icon: <FcLinux />, name: "Linux", colorClassName: "" },
  //4
  { icon: <FaHtml5 />, name: "HTML", colorClassName: "text-orange-600" },
  { icon: <FaCss3Alt />, name: "CSS", colorClassName: "text-blue-600" },
  { icon: <FaJs />, name: "JavaScript", colorClassName: "text-yellow-600" },
  { icon: <FaReact />, name: "React", colorClassName: "text-cyan-400" },
  { icon: <RiNextjsFill />, name: "Next.js", colorClassName: "text-black dark:text-white" },
  { icon: <RiTailwindCssFill />, name: "Tailwind CSS", colorClassName: "text-[#00FFFF]" },
  { icon: <FaNodeJs />, name: "Node.js", colorClassName: "text-green-600" },
  { icon: <SiTypescript />, name: "TypeScript", colorClassName: "text-[#377CC8]" },
  { icon: <SiExpress />, name: "Express", colorClassName: "text-black dark:text-white" },
  { icon: <SiZod />, name: "Zod", colorClassName: "text-blue-500"},
  { icon: <SiPrisma />, name: "Prisma", colorClassName: "text-[#000] dark:text-white" },
  { icon: <SiSqlalchemy />, name: "SQL Alchemy", colorClassName: "text-[#000] dark:text-white" },
  { icon: <FaPython />, name: "Python", colorClassName: "text-[#08668E]" },
  { icon: <SiDjango />, name: "Django", colorClassName: "text-[#2DA045]" },
  { icon: <SiFastapi />, name: "FastAPI", colorClassName: "text-[#39979c]" },
  { icon: <SiFlask />, name: "Flask", colorClassName: "text-black dark:text-white" },
  { icon: <SiRedis />, name: "Redis", colorClassName: "text-red-500" },
  { icon: <FaDocker />, name: "Docker", colorClassName: "text-blue-500" },
  { icon: <FaGitAlt />, name: "Git", colorClassName: "text-red-600" },
  { icon: <FaGithub />, name: "GitHub", colorClassName: "text-black dark:text-white" },
  { icon: <BiLogoPostgresql />, name: "PostgreSQL", colorClassName: "text-[#396C94]" },
  { icon: <SiMongodb />, name: "MongoDB", colorClassName: "text-[#2DA045]" },
  { icon: <SiJsonwebtokens />, name: "JSON Web Tokens", colorClassName: "text-[#EA185D]" },
  { icon: <FcLinux />, name: "Linux", colorClassName: "" },
  //5
  { icon: <FaHtml5 />, name: "HTML", colorClassName: "text-orange-600" },
  { icon: <FaCss3Alt />, name: "CSS", colorClassName: "text-blue-600" },
  { icon: <FaJs />, name: "JavaScript", colorClassName: "text-yellow-600" },
  { icon: <FaReact />, name: "React", colorClassName: "text-cyan-400" },
  { icon: <RiNextjsFill />, name: "Next.js", colorClassName: "text-black dark:text-white" },
  { icon: <RiTailwindCssFill />, name: "Tailwind CSS", colorClassName: "text-[#00FFFF]" },
  { icon: <FaNodeJs />, name: "Node.js", colorClassName: "text-green-600" },
  { icon: <SiTypescript />, name: "TypeScript", colorClassName: "text-[#377CC8]" },
  { icon: <SiExpress />, name: "Express", colorClassName: "text-black dark:text-white" },
  { icon: <SiZod />, name: "Zod", colorClassName: "text-blue-500"},
  { icon: <SiPrisma />, name: "Prisma", colorClassName: "text-[#000] dark:text-white" },
  { icon: <SiSqlalchemy />, name: "SQL Alchemy", colorClassName: "text-[#000] dark:text-white" },
  { icon: <FaPython />, name: "Python", colorClassName: "text-[#08668E]" },
  { icon: <SiDjango />, name: "Django", colorClassName: "text-[#2DA045]" },
  { icon: <SiFastapi />, name: "FastAPI", colorClassName: "text-[#39979c]" },
  { icon: <SiFlask />, name: "Flask", colorClassName: "text-black dark:text-white" },
  { icon: <SiRedis />, name: "Redis", colorClassName: "text-red-500" },
  { icon: <FaDocker />, name: "Docker", colorClassName: "text-blue-500" },
  { icon: <FaGitAlt />, name: "Git", colorClassName: "text-red-600" },
  { icon: <FaGithub />, name: "GitHub", colorClassName: "text-black dark:text-white" },
  { icon: <BiLogoPostgresql />, name: "PostgreSQL", colorClassName: "text-[#396C94]" },
  { icon: <SiMongodb />, name: "MongoDB", colorClassName: "text-[#2DA045]" },
  { icon: <SiJsonwebtokens />, name: "JSON Web Tokens", colorClassName: "text-[#EA185D]" },
  { icon: <FcLinux />, name: "Linux", colorClassName: "" },
];
