import {
  FaJs,
  FaReact,
  FaNodeJs,
  FaDocker,
  FaCss3Alt,
  FaHtml5,
  FaGitAlt,
  FaGithub,
  FaBootstrap,
  FaPython,
  FaAngular,
  FaJava,
  FaJenkins,
} from "react-icons/fa";
import {
  SiPrisma,
  SiMongodb,
  SiRedis,
  SiExpress,
  SiTypescript,
  SiRabbitmq,
  SiJsonwebtokens,
  SiZod,
  SiDjango,
  SiFastapi,
  SiFlask,
  SiSqlalchemy,
  SiSpring,
  SiSpringboot,
  SiSpringsecurity,
  SiSpringCreators
} from "react-icons/si";
import { RiNextjsFill } from "react-icons/ri";
import { RiTailwindCssFill } from "react-icons/ri";
import { BiLogoPostgresql } from "react-icons/bi";
import { FcLinux } from "react-icons/fc";

export const ICONS = [
  //1
  {icon: <FaJava />, name: "Java", colorClassName: "text-red-600"},
  { icon: <FaPython />, name: "Python", colorClassName: "text-[#08668E]" },
  { icon: <SiTypescript />, name: "TypeScript", colorClassName: "text-[#377CC8]" },
  { icon: <SiSpring />, name: "Spring", colorClassName: "text-green-600"},
  { icon: <SiSpringboot />, name: "Spring Boot", colorClassName: "text-green-600"},
  { icon: <SiSpringsecurity />, name: "Spring Security", colorClassName: "text-green-600"},
  { icon: <FaNodeJs />, name: "Node.js", colorClassName: "text-green-600" },
  { icon: <FaAngular />, name: "Angular", colorClassName: "text-red-600"},
  { icon: <FaReact />, name: "React", colorClassName: "text-cyan-400" },
  { icon: <RiNextjsFill />, name: "Next.js", colorClassName: "text-black dark:text-white" },
  { icon: <SiFastapi />, name: "FastAPI", colorClassName: "text-[#39979c]" },
  { icon: <SiRedis />, name: "Redis", colorClassName: "text-red-500" },
  { icon: <FaDocker />, name: "Docker", colorClassName: "text-blue-500" },
  { icon: <FaGitAlt />, name: "Git", colorClassName: "text-red-600" },
  { icon: <FaGithub />, name: "GitHub", colorClassName: "text-black dark:text-white" },
  { icon: <BiLogoPostgresql />, name: "PostgreSQL", colorClassName: "text-[#396C94]" },
  { icon: <SiMongodb />, name: "MongoDB", colorClassName: "text-[#2DA045]" },
  { icon: <SiJsonwebtokens />, name: "JSON Web Tokens", colorClassName: "text-[#EA185D]" },
  { icon: <FcLinux />, name: "Linux", colorClassName: "" },
  { icon: <FaJenkins />, name: "Jenkins", colorClassName: "text-blue-500" },

  //2
  
  {icon: <FaJava />, name: "Java", colorClassName: "text-red-600"},
  { icon: <FaPython />, name: "Python", colorClassName: "text-[#08668E]" },
  { icon: <SiTypescript />, name: "TypeScript", colorClassName: "text-[#377CC8]" },
  { icon: <SiSpring />, name: "Spring", colorClassName: "text-green-600"},
  { icon: <SiSpringboot />, name: "Spring Boot", colorClassName: "text-green-600"},
  { icon: <SiSpringsecurity />, name: "Spring Security", colorClassName: "text-green-600"},
  { icon: <FaNodeJs />, name: "Node.js", colorClassName: "text-green-600" },
  { icon: <FaAngular />, name: "Angular", colorClassName: "text-red-600"},
  { icon: <FaReact />, name: "React", colorClassName: "text-cyan-400" },
  { icon: <RiNextjsFill />, name: "Next.js", colorClassName: "text-black dark:text-white" },
  { icon: <SiFastapi />, name: "FastAPI", colorClassName: "text-[#39979c]" },
  { icon: <SiRedis />, name: "Redis", colorClassName: "text-red-500" },
  { icon: <FaDocker />, name: "Docker", colorClassName: "text-blue-500" },
  { icon: <FaGitAlt />, name: "Git", colorClassName: "text-red-600" },
  { icon: <FaGithub />, name: "GitHub", colorClassName: "text-black dark:text-white" },
  { icon: <BiLogoPostgresql />, name: "PostgreSQL", colorClassName: "text-[#396C94]" },
  { icon: <SiMongodb />, name: "MongoDB", colorClassName: "text-[#2DA045]" },
  { icon: <SiJsonwebtokens />, name: "JSON Web Tokens", colorClassName: "text-[#EA185D]" },
  { icon: <FcLinux />, name: "Linux", colorClassName: "" },
  { icon: <FaJenkins />, name: "Jenkins", colorClassName: "text-blue-500" },
  //3
 
  {icon: <FaJava />, name: "Java", colorClassName: "text-red-600"},
  { icon: <FaPython />, name: "Python", colorClassName: "text-[#08668E]" },
  { icon: <SiTypescript />, name: "TypeScript", colorClassName: "text-[#377CC8]" },
  { icon: <SiSpring />, name: "Spring", colorClassName: "text-green-600"},
  { icon: <SiSpringboot />, name: "Spring Boot", colorClassName: "text-green-600"},
  { icon: <SiSpringsecurity />, name: "Spring Security", colorClassName: "text-green-600"},
  { icon: <FaNodeJs />, name: "Node.js", colorClassName: "text-green-600" },
  { icon: <FaAngular />, name: "Angular", colorClassName: "text-red-600"},
  { icon: <FaReact />, name: "React", colorClassName: "text-cyan-400" },
  { icon: <RiNextjsFill />, name: "Next.js", colorClassName: "text-black dark:text-white" },
  { icon: <SiFastapi />, name: "FastAPI", colorClassName: "text-[#39979c]" },
  { icon: <SiRedis />, name: "Redis", colorClassName: "text-red-500" },
  { icon: <FaDocker />, name: "Docker", colorClassName: "text-blue-500" },
  { icon: <FaGitAlt />, name: "Git", colorClassName: "text-red-600" },
  { icon: <FaGithub />, name: "GitHub", colorClassName: "text-black dark:text-white" },
  { icon: <BiLogoPostgresql />, name: "PostgreSQL", colorClassName: "text-[#396C94]" },
  { icon: <SiMongodb />, name: "MongoDB", colorClassName: "text-[#2DA045]" },
  { icon: <SiJsonwebtokens />, name: "JSON Web Tokens", colorClassName: "text-[#EA185D]" },
  { icon: <FcLinux />, name: "Linux", colorClassName: "" },
  { icon: <FaJenkins />, name: "Jenkins", colorClassName: "text-blue-500" },
  //4
  
  {icon: <FaJava />, name: "Java", colorClassName: "text-red-600"},
  { icon: <FaPython />, name: "Python", colorClassName: "text-[#08668E]" },
  { icon: <SiTypescript />, name: "TypeScript", colorClassName: "text-[#377CC8]" },
  { icon: <SiSpring />, name: "Spring", colorClassName: "text-green-600"},
  { icon: <SiSpringboot />, name: "Spring Boot", colorClassName: "text-green-600"},
  { icon: <SiSpringsecurity />, name: "Spring Security", colorClassName: "text-green-600"},
  { icon: <FaNodeJs />, name: "Node.js", colorClassName: "text-green-600" },
  { icon: <FaAngular />, name: "Angular", colorClassName: "text-red-600"},
  { icon: <FaReact />, name: "React", colorClassName: "text-cyan-400" },
  { icon: <RiNextjsFill />, name: "Next.js", colorClassName: "text-black dark:text-white" },
  { icon: <SiFastapi />, name: "FastAPI", colorClassName: "text-[#39979c]" },
  { icon: <SiRedis />, name: "Redis", colorClassName: "text-red-500" },
  { icon: <FaDocker />, name: "Docker", colorClassName: "text-blue-500" },
  { icon: <FaGitAlt />, name: "Git", colorClassName: "text-red-600" },
  { icon: <FaGithub />, name: "GitHub", colorClassName: "text-black dark:text-white" },
  { icon: <BiLogoPostgresql />, name: "PostgreSQL", colorClassName: "text-[#396C94]" },
  { icon: <SiMongodb />, name: "MongoDB", colorClassName: "text-[#2DA045]" },
  { icon: <SiJsonwebtokens />, name: "JSON Web Tokens", colorClassName: "text-[#EA185D]" },
  { icon: <FcLinux />, name: "Linux", colorClassName: "" },
  { icon: <FaJenkins />, name: "Jenkins", colorClassName: "text-blue-500" },
  //5
  
  {icon: <FaJava />, name: "Java", colorClassName: "text-red-600"},
  { icon: <FaPython />, name: "Python", colorClassName: "text-[#08668E]" },
  { icon: <SiTypescript />, name: "TypeScript", colorClassName: "text-[#377CC8]" },
  { icon: <SiSpring />, name: "Spring", colorClassName: "text-green-600"},
  { icon: <SiSpringboot />, name: "Spring Boot", colorClassName: "text-green-600"},
  { icon: <SiSpringsecurity />, name: "Spring Security", colorClassName: "text-green-600"},
  { icon: <FaNodeJs />, name: "Node.js", colorClassName: "text-green-600" },
  { icon: <FaAngular />, name: "Angular", colorClassName: "text-red-600"},
  { icon: <FaReact />, name: "React", colorClassName: "text-cyan-400" },
  { icon: <RiNextjsFill />, name: "Next.js", colorClassName: "text-black dark:text-white" },
  { icon: <SiFastapi />, name: "FastAPI", colorClassName: "text-[#39979c]" },
  { icon: <SiRedis />, name: "Redis", colorClassName: "text-red-500" },
  { icon: <FaDocker />, name: "Docker", colorClassName: "text-blue-500" },
  { icon: <FaGitAlt />, name: "Git", colorClassName: "text-red-600" },
  { icon: <FaGithub />, name: "GitHub", colorClassName: "text-black dark:text-white" },
  { icon: <BiLogoPostgresql />, name: "PostgreSQL", colorClassName: "text-[#396C94]" },
  { icon: <SiMongodb />, name: "MongoDB", colorClassName: "text-[#2DA045]" },
  { icon: <SiJsonwebtokens />, name: "JSON Web Tokens", colorClassName: "text-[#EA185D]" },
  { icon: <FcLinux />, name: "Linux", colorClassName: "" },
  { icon: <FaJenkins />, name: "Jenkins", colorClassName: "text-blue-500" },
];
