import {
  FaJs,
  FaReact,
  FaNodeJs,
  FaDocker,
  FaCss3Alt,
  FaHtml5,
  FaGitAlt,
  FaGithub,
  FaBootstrap,
  FaPython,
} from "react-icons/fa";
import {
  SiFastify,
  SiMysql,
  SiPrisma,
  SiMongodb,
  SiRedis,
  SiExpress,
  SiTypescript,
  SiKnexdotjs,
  SiRabbitmq,
  SiJsonwebtokens,
  SiZod,
  SiDjango,
  SiFastapi,
  SiFlask,
} from "react-icons/si";
import { RiNextjsFill } from "react-icons/ri";
import { RiTailwindCssFill } from "react-icons/ri";
import { BiLogoPostgresql } from "react-icons/bi";
import { FcLinux } from "react-icons/fc";

export const ICONS = [
  { icon: <FaHtml5 />, colorClassName: "text-orange-600" },
  { icon: <FaCss3Alt />, colorClassName: "text-blue-600" },
  { icon: <FaJs />, colorClassName: "text-yellow-600" },
  { icon: <FaReact />, colorClassName: "text-cyan-400" },
  { icon: <RiNextjsFill />, colorClassName: "text-black dark:text-white" },
  { icon: <RiTailwindCssFill />, colorClassName: "text-[#00FFFF]" },
  { icon: <FaNodeJs />, colorClassName: "text-green-600" },
  { icon: <SiTypescript />, colorClassName: "text-[#377CC8]" },
  { icon: <SiExpress />, colorClassName: "text-black dark:text-white" },
  { icon: <SiPrisma />, colorClassName: "text-[#000] dark:text-white" },
  { icon: <FaPython />, colorClassName: "text-[#08668E]" },
  { icon: <SiDjango />, colorClassName: "text-[#2DA045]" },
  { icon: <SiFastapi />, colorClassName: "text-[#39979c]" },
  { icon: <SiFlask />, colorClassName: "text-black dark:text-white" },
  { icon: <FaDocker />, colorClassName: "text-blue-500" },
  { icon: <FaGitAlt />, colorClassName: "text-red-600" },
  { icon: <FaGithub />, colorClassName: "text-black dark:text-white" },
  { icon: <BiLogoPostgresql />, colorClassName: "text-[#396C94]" },
  { icon: <SiMongodb />, colorClassName: "text-[#2DA045]" },
  { icon: <SiJsonwebtokens />, colorClassName: "text-[#EA185D]" },
  { icon: <FcLinux />, colorClassName: "" },

  //2
  { icon: <FaHtml5 />, colorClassName: "text-orange-600" },
  { icon: <FaCss3Alt />, colorClassName: "text-blue-600" },
  { icon: <FaJs />, colorClassName: "text-yellow-600" },
  { icon: <FaReact />, colorClassName: "text-cyan-400" },
  { icon: <RiNextjsFill />, colorClassName: "text-black dark:text-white" },
  { icon: <RiTailwindCssFill />, colorClassName: "text-[#00FFFF]" },
  { icon: <FaNodeJs />, colorClassName: "text-green-600" },
  { icon: <SiTypescript />, colorClassName: "text-[#377CC8]" },
  { icon: <SiExpress />, colorClassName: "text-black dark:text-white" },
  { icon: <SiPrisma />, colorClassName: "text-[#000] dark:text-white" },
  { icon: <FaPython />, colorClassName: "text-[#08668E]" },
  { icon: <SiDjango />, colorClassName: "text-[#2DA045]" },
  { icon: <SiFastapi />, colorClassName: "text-[#39979c]" },
  { icon: <SiFlask />, colorClassName: "text-black dark:text-white" },
  { icon: <FaDocker />, colorClassName: "text-blue-500" },
  { icon: <FaGitAlt />, colorClassName: "text-red-600" },
  { icon: <FaGithub />, colorClassName: "text-black dark:text-white" },
  { icon: <BiLogoPostgresql />, colorClassName: "text-[#396C94]" },
  { icon: <SiMongodb />, colorClassName: "text-[#2DA045]" },
  { icon: <SiJsonwebtokens />, colorClassName: "text-[#EA185D]" },
  { icon: <FcLinux />, colorClassName: "" },
  //3
  { icon: <FaHtml5 />, colorClassName: "text-orange-600" },
  { icon: <FaCss3Alt />, colorClassName: "text-blue-600" },
  { icon: <FaJs />, colorClassName: "text-yellow-600" },
  { icon: <FaReact />, colorClassName: "text-cyan-400" },
  { icon: <RiNextjsFill />, colorClassName: "text-black dark:text-white" },
  { icon: <RiTailwindCssFill />, colorClassName: "text-[#00FFFF]" },
  { icon: <FaNodeJs />, colorClassName: "text-green-600" },
  { icon: <SiTypescript />, colorClassName: "text-[#377CC8]" },
  { icon: <SiExpress />, colorClassName: "text-black dark:text-white" },
  { icon: <SiPrisma />, colorClassName: "text-[#000] dark:text-white" },
  { icon: <FaPython />, colorClassName: "text-[#08668E]" },
  { icon: <SiDjango />, colorClassName: "text-[#2DA045]" },
  { icon: <SiFastapi />, colorClassName: "text-[#39979c]" },
  { icon: <SiFlask />, colorClassName: "text-black dark:text-white" },
  { icon: <FaDocker />, colorClassName: "text-blue-500" },
  { icon: <FaGitAlt />, colorClassName: "text-red-600" },
  { icon: <FaGithub />, colorClassName: "text-black dark:text-white" },
  { icon: <BiLogoPostgresql />, colorClassName: "text-[#396C94]" },
  { icon: <SiMongodb />, colorClassName: "text-[#2DA045]" },
  { icon: <SiJsonwebtokens />, colorClassName: "text-[#EA185D]" },
  { icon: <FcLinux />, colorClassName: "" },

  //4
  { icon: <FaHtml5 />, colorClassName: "text-orange-600" },
  { icon: <FaCss3Alt />, colorClassName: "text-blue-600" },
  { icon: <FaJs />, colorClassName: "text-yellow-600" },
  { icon: <FaReact />, colorClassName: "text-cyan-400" },
  { icon: <RiNextjsFill />, colorClassName: "text-black dark:text-white" },
  { icon: <RiTailwindCssFill />, colorClassName: "text-[#00FFFF]" },
  { icon: <FaNodeJs />, colorClassName: "text-green-600" },
  { icon: <SiTypescript />, colorClassName: "text-[#377CC8]" },
  { icon: <SiExpress />, colorClassName: "text-black dark:text-white" },
  { icon: <SiPrisma />, colorClassName: "text-[#000] dark:text-white" },
  { icon: <FaPython />, colorClassName: "text-[#08668E]" },
  { icon: <SiDjango />, colorClassName: "text-[#2DA045]" },
  { icon: <SiFastapi />, colorClassName: "text-[#39979c]" },
  { icon: <SiFlask />, colorClassName: "text-black dark:text-white" },
  { icon: <FaDocker />, colorClassName: "text-blue-500" },
  { icon: <FaGitAlt />, colorClassName: "text-red-600" },
  { icon: <FaGithub />, colorClassName: "text-black dark:text-white" },
  { icon: <BiLogoPostgresql />, colorClassName: "text-[#396C94]" },
  { icon: <SiMongodb />, colorClassName: "text-[#2DA045]" },
  { icon: <SiJsonwebtokens />, colorClassName: "text-[#EA185D]" },
  { icon: <FcLinux />, colorClassName: "" },
  //5
  { icon: <FaHtml5 />, colorClassName: "text-orange-600" },
  { icon: <FaCss3Alt />, colorClassName: "text-blue-600" },
  { icon: <FaJs />, colorClassName: "text-yellow-600" },
  { icon: <FaReact />, colorClassName: "text-cyan-400" },
  { icon: <RiNextjsFill />, colorClassName: "text-black dark:text-white" },
  { icon: <RiTailwindCssFill />, colorClassName: "text-[#00FFFF]" },
  { icon: <FaNodeJs />, colorClassName: "text-green-600" },
  { icon: <SiTypescript />, colorClassName: "text-[#377CC8]" },
  { icon: <SiExpress />, colorClassName: "text-black dark:text-white" },
  { icon: <SiPrisma />, colorClassName: "text-[#000] dark:text-white" },
  { icon: <FaPython />, colorClassName: "text-[#08668E]" },
  { icon: <SiDjango />, colorClassName: "text-[#2DA045]" },
  { icon: <SiFastapi />, colorClassName: "text-[#39979c]" },
  { icon: <SiFlask />, colorClassName: "text-black dark:text-white" },
  { icon: <FaDocker />, colorClassName: "text-blue-500" },
  { icon: <FaGitAlt />, colorClassName: "text-red-600" },
  { icon: <FaGithub />, colorClassName: "text-black dark:text-white" },
  { icon: <BiLogoPostgresql />, colorClassName: "text-[#396C94]" },
  { icon: <SiMongodb />, colorClassName: "text-[#2DA045]" },
  { icon: <SiJsonwebtokens />, colorClassName: "text-[#EA185D]" },
  { icon: <FcLinux />, colorClassName: "" },
];
